server:
  port: 3000
  servlet:
    context-path: /

spring:
  application:
    name: gateway_service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  rabbitmq:
    username: root
    password: root
    host: localhost
    port:
      - 15672

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # lb = load balancing
          predicates:
            - Path=/user/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

  main:
    web-application-type: reactive