version: '3'

services:
  mysql-master:
    image: mysql:8.0.32
    container_name: shopify-sql
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql-master/data:/var/lib/mysql
      - /root/mysql-master/log:/var/log/mysql
      - /root/mysql-master/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mq:
    image: rabbitmq:3-management
    container_name: shopify-mq
    hostname: mq1
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

  myredis:
    image: redis
    container_name: shopify-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: unless-stopped

  es:
    image: elasticsearch:7.12.1
    container_name: shopify-es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    privileged: true
    networks:
      - es-net
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  kibana:
    image: kibana:7.12.1
    container_name: shopify-kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es:9200"
    networks:
      - es-net
    ports:
      - "5601:5601"
    restart: unless-stopped

  consul:
    image: consul:latest
    container_name: shopify-consul
    ports:
      - "8500:8500"
    command: consul agent -dev -bootstrap-expect=1 -client=0.0.0.0
    restart: always

networks:
  es-net:
volumes:
  es-data:
  es-plugins: