server:
  port: 3005
  servlet:
    context-path: /

spring:
  application:
    name: catagory_service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      ribbon:
        enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:store_category.sql
      platform: mysql

  rabbitmq:
    username: root
    password: root
    host: localhost
    port:
      - 15672

  datasource:
    url: jdbc:mysql://localhost:3306/store_category?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50